version: "3.11"

services:
  djangoapp:
    build: .
    command: >
      sh -c "
        python manage.py makemigrations users tasks &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A taskmanager worker --loglevel=info
    depends_on:
      - redis
      - djangoapp

  celery-beat:
    build: .
    command: celery -A taskmanager beat --loglevel=info
    depends_on:
      - redis
      - djangoapp

volumes:
  pgdata: